field_map_1 = {
    "report_title": "[name='title']",
    "valuation_purpose": "[name='purpose_id']",
    "value_premise": "[name='value_premise_id']",
    "value_base": "[name='value_base_id']",
    "report_type": "[name='report_type']",
    "valuation_date": "[name='valued_at']",
    "report_issuing_date": "[name='submitted_at']",
    "assumptions": "[name='assumptions']",
    "special_assumptions": "[name='special_assumptions']",
    "final_value": "[name='value']",
    "valuation_currency": "[name='currency_id']",
    "report_asset_file": "[name='report_file']",
    "client_name": "[name='client[0][name]']",
    "telephone_number": "[name='client[0][telephone]']",
    "email_address": "[name='client[0][email]']",
    "has_other_users": "[name='has_user']",
    "valuer_name": "[name='valuer[0][id]']",
    "contribution_percentage": "[name='valuer[0][contribution]']",
}

field_types_1 = {
    "report_title": "text",
    "valuation_purpose": "select",
    "value_premise": "select",
    "value_base": "select",
    "report_type": "radio",
    "valuation_date": "text",
    "report_issuing_date": "text",
    "assumptions": "text",
    "special_assumptions": "text",
    "final_value": "text",
    "valuation_currency": "select",
    "report_asset_file": "file",
    "client_name": "text",
    "telephone_number": "text",
    "email_address": "text",
    "has_other_users": "checkbox",
    "valuer_name": "select",
    "contribution_percentage": "select",
}

field_map_2 = {
    "asset_type": "[name='asset_type_id']",
    "inspection_date": "[name='inspected_at']",
    "final_value": "[name='value']",
    "market_approach": "[id='approach1']",
    "comparable_transactions_method": "[name='approach[1][method][1][value]']",
    "income_approach": "[id='approach2']",
    "profit_method": "[name='approach[2][method][5][value]']",
    "cost_approach": "[id='approach3']",
    "summation_method": "[name='approach[3][method][11][value]']",
    "longitude": "[name='longitude']",
    "latitude": "[name='latitude']",
    "asset_usage_sector": "[name='asset_usage_id']",
    "country": "[id='country_id']",
    "region": "[id='region']",
    "city": "[id='city']",
}

field_types_2 = {
    "asset_type": "dynamic_select",
    "inspection_date": "text",
    "final_value": "text",
    "market_approach": "select",
    "comparable_transactions_method": "text",
    "income_approach": "select",
    "profit_method": "text",
    "cost_approach": "select",
    "summation_method": "text",
    "longitude": "text",
    "latitude": "text",
    "asset_usage_sector": "dynamic_select",
    "country": "location",
    "region": "location",
    "city": "location",
}

field_map_3 = {
    "block_number": "[name='attribute[1]']",
    "property_number": "[name='attribute[2]']",
    "certificate_number": "[name='attribute[3]']",
    "ownership_type": "[name='attribute[4]']",
    "ownership_percentage": "[name='attribute[5]']",
    "rental_duration": "[name='attribute[6]']",
    "rental_end_date": "[name='attribute[7]']",
    "street_facing_fronts": "[name='attribute[8]']",
    "distance_from_city_center": "[name='attribute[9]']",
    "facilities": "[name='attribute[10][]']",
    "land_area": "[name='attribute[11]']",
    "building_area": "[name='attribute[12]']",
    "authorized_land_cover_percentage": "[name='attribute[13]']",
    "authorized_height": "[name='attribute[14]']",
    "land_leased": "[id='15']",
    "building_status": "[name='attribute[16]']",
    "finishing_status": "[name='attribute[17]']",
    "furnishing_status": "[name='attribute[18]']",
    "air_conditioning": "[name='attribute[19]']",
    "building_type": "[name='attribute[20]']",
    "other_features": "[name='attribute[21][]']",
    "best_use": "[name='attribute[27]']",
    "asset_age": "[name='attribute[28]']",
    "street_width": "[name='attribute[31]']",
}

field_types_3 = {
    "block_number": "text",
    "property_number": "text",
    "certificate_number": "text",
    "ownership_type": "select",
    "ownership_percentage": "text",
    "rental_duration": "text",
    "rental_end_date": "text",
    "street_facing_fronts": "select",
    "distance_from_city_center": "text",
    "facilities": "checkbox",
    "land_area": "text",
    "building_area": "text",
    "authorized_land_cover_percentage": "text",
    "authorized_height": "text",
    "land_leased": "radio",
    "building_status": "select",
    "finishing_status": "select",
    "furnishing_status": "select",
    "air_conditioning": "select",
    "building_type": "select",
    "other_features": "checkbox",
    "best_use": "radio",
    "asset_age": "text",
    "street_width": "text"
}

form_steps = [
    {"field_map": field_map_1, "field_types": field_types_1},
    {"field_map": field_map_2, "field_types": field_types_2},
    {"field_map": field_map_3, "field_types": field_types_3},
]